apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: production
  labels:
    app: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        image: samba1236/spring-boot:kubernetes
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: production
  labels:
    app: springboot
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
  selector:
    app: springboot
